// Code generated by "callbackgen -type=TWAPWorker -output=twap_callbacks.go"; DO NOT EDIT.

package xfundingv2

import (
	"github.com/c9s/bbgo/pkg/types"
)

func (w *TWAPWorker) OnNotify(cb func(trade types.Trade)) {
	w.notifyCallbacks = append(w.notifyCallbacks, cb)
}

func (w *TWAPWorker) EmitNotify(trade types.Trade) {
	for _, cb := range w.notifyCallbacks {
		cb(trade)
	}
}
