// Code generated by "stringer -type=TWAPWorkerState"; DO NOT EDIT.

package xfundingv2

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TWAPWorkerStatePending-0]
	_ = x[TWAPWorkerStateRunning-1]
	_ = x[TWAPWorkerStateDone-2]
}

const _TWAPWorkerState_name = "TWAPWorkerStatePendingTWAPWorkerStateRunningTWAPWorkerStateDone"

var _TWAPWorkerState_index = [...]uint8{0, 22, 44, 63}

func (i TWAPWorkerState) String() string {
	if i < 0 || i >= TWAPWorkerState(len(_TWAPWorkerState_index)-1) {
		return "TWAPWorkerState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TWAPWorkerState_name[_TWAPWorkerState_index[i]:_TWAPWorkerState_index[i+1]]
}
