// Code generated by "callbackgen -type=TWAPWorker -output=twap_callbacks.go"; DO NOT EDIT.

package xfundingv2

import (
	"github.com/c9s/bbgo/pkg/types"
)

func (w *TWAPWorker) OnTrade(cb func(trade types.Trade)) {
	w.tradeCallbacks = append(w.tradeCallbacks, cb)
}

func (w *TWAPWorker) EmitTrade(trade types.Trade) {
	for _, cb := range w.tradeCallbacks {
		cb(trade)
	}
}
